export const GET_CHALLENGES='GET_CHALLENGES';
export const SET_CHALLENGES='SET_CHALLENGES';
export const SOLVE_CHALLENGE_REQUESTING='SOLVE_CHALLENGE';
export const SET_SOLVE_CHALLENGE_RESULT='SET_SOLVE_CHALLENGE_RESULT';
export const RESET_SOLVE_CHALLENGE='RESET_SOLVE_CHALLENGE';