export const SET_PUBLIC_CONTACTS='SET_PUBLIC_CONTACTS';
export const GET_PUBLIC_CONTACTS='GET_PUBLIC_CONTACTS';
export const SET_PERSONAL_CONTACTS='SET_PERSONAL_CONTACTS';
export const GET_PERSONAL_CONTACTS='GET_PERSONAL_CONTACTS';
export const SET_USER ='SET_USER';
export const ADD_CONTACT_TO_FRIEND_LIST='ADD_CONTACT_TO_FRIEND_LIST';