export const SET_PUBLIC_CONTACTS='SET_PUBLIC_CONTACTS';
export const GET_PUBLIC_CONTACTS='GET_PUBLIC_CONTACTS';
export const SET_FRIEND_LIST='SET_FRIEND_LIST';
export const GET_FRIEND_LIST='GET_FRIEND_LIST';
export const SET_USER ='SET_USER';
export const ADD_CONTACT_TO_FRIEND_LIST='ADD_CONTACT_TO_FRIEND_LIST';