export const LOGIN_REQUESTING='LOGIN_REQUESTING';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_ERROR='LOGIN_ERROR';
export const RESEND_ACTIVATION_MAIL='RESEND_ACTIVTION_MAIL';
export const RESEND_ACTIVATION_MAIL_RESPONSE='RESENS_ACTIVATION_MAIL_RESPONSE';